// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VelvetLeaves.Data;

#nullable disable

namespace VelvetLeaves.Data.Migrations
{
    [DbContext(typeof(VelvetLeavesDbContext))]
    [Migration("20230802070404_AddedForeignKeyForAddressUserAndMadeZipCodeOptional")]
    partial class AddedForeignKeyForAddressUserAndMadeZipCodeOptional
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ApplicationUserProduct", b =>
                {
                    b.Property<string>("ApplicationUsersId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("FavoritesId")
                        .HasColumnType("int");

                    b.HasKey("ApplicationUsersId", "FavoritesId");

                    b.HasIndex("FavoritesId");

                    b.ToTable("ApplicationUserProduct");
                });

            modelBuilder.Entity("ColorProductSeries", b =>
                {
                    b.Property<int>("DefaultColorsId")
                        .HasColumnType("int");

                    b.Property<int>("ProductSeriesId")
                        .HasColumnType("int");

                    b.HasKey("DefaultColorsId", "ProductSeriesId");

                    b.HasIndex("ProductSeriesId");

                    b.ToTable("ColorProductSeries");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("OrderProduct", b =>
                {
                    b.Property<Guid>("OrdersId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ProductsId")
                        .HasColumnType("int");

                    b.HasKey("OrdersId", "ProductsId");

                    b.HasIndex("ProductsId");

                    b.ToTable("OrderProduct");
                });

            modelBuilder.Entity("ProductsColors", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("ColorId")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "ColorId");

                    b.HasIndex("ColorId");

                    b.ToTable("ProductsColors");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            ColorId = 1
                        },
                        new
                        {
                            ProductId = 2,
                            ColorId = 1
                        },
                        new
                        {
                            ProductId = 2,
                            ColorId = 2
                        },
                        new
                        {
                            ProductId = 3,
                            ColorId = 3
                        },
                        new
                        {
                            ProductId = 4,
                            ColorId = 2
                        });
                });

            modelBuilder.Entity("ProductsMaterials", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("MaterialId")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "MaterialId");

                    b.HasIndex("MaterialId");

                    b.ToTable("ProductsMaterials");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            MaterialId = 1
                        },
                        new
                        {
                            ProductId = 2,
                            MaterialId = 2
                        },
                        new
                        {
                            ProductId = 3,
                            MaterialId = 1
                        },
                        new
                        {
                            ProductId = 4,
                            MaterialId = 1
                        },
                        new
                        {
                            ProductId = 4,
                            MaterialId = 3
                        },
                        new
                        {
                            ProductId = 5,
                            MaterialId = 4
                        },
                        new
                        {
                            ProductId = 6,
                            MaterialId = 4
                        },
                        new
                        {
                            ProductId = 7,
                            MaterialId = 4
                        });
                });

            modelBuilder.Entity("ProductsSeriesMaterials", b =>
                {
                    b.Property<int>("ProductSeriesId")
                        .HasColumnType("int");

                    b.Property<int>("MaterialId")
                        .HasColumnType("int");

                    b.HasKey("ProductSeriesId", "MaterialId");

                    b.HasIndex("MaterialId");

                    b.ToTable("ProductsSeriesMaterials");

                    b.HasData(
                        new
                        {
                            ProductSeriesId = 1,
                            MaterialId = 1
                        },
                        new
                        {
                            ProductSeriesId = 2,
                            MaterialId = 2
                        },
                        new
                        {
                            ProductSeriesId = 3,
                            MaterialId = 1
                        },
                        new
                        {
                            ProductSeriesId = 4,
                            MaterialId = 3
                        },
                        new
                        {
                            ProductSeriesId = 5,
                            MaterialId = 4
                        },
                        new
                        {
                            ProductSeriesId = 6,
                            MaterialId = 4
                        });
                });

            modelBuilder.Entity("ProductsSeriesTags", b =>
                {
                    b.Property<int>("ProductSeriesId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("ProductSeriesId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("ProductsSeriesTags");

                    b.HasData(
                        new
                        {
                            ProductSeriesId = 1,
                            TagId = 2
                        },
                        new
                        {
                            ProductSeriesId = 2,
                            TagId = 2
                        },
                        new
                        {
                            ProductSeriesId = 3,
                            TagId = 2
                        },
                        new
                        {
                            ProductSeriesId = 5,
                            TagId = 1
                        },
                        new
                        {
                            ProductSeriesId = 6,
                            TagId = 1
                        });
                });

            modelBuilder.Entity("ProductsTags", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("ProductsTags");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            TagId = 2
                        },
                        new
                        {
                            ProductId = 2,
                            TagId = 2
                        },
                        new
                        {
                            ProductId = 3,
                            TagId = 2
                        },
                        new
                        {
                            ProductId = 5,
                            TagId = 1
                        },
                        new
                        {
                            ProductId = 6,
                            TagId = 1
                        });
                });

            modelBuilder.Entity("VelvetLeaves.Data.Models.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("StreetAddress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("ZipCode")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("VelvetLeaves.Data.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "38b01a65-9ff5-40f5-b6dc-db506b06b964",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "4c35a003-c624-4952-b555-b54c4bf213f2",
                            Email = "user@vls.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "USER@VLS.COM",
                            NormalizedUserName = "USER@VLS.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEPC5IWEn6voDizaDSQEbpqyWRerZiXMsBjfXoZ2tn8z8eTFpeZ2ndCHKS7pnfd0WkA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "4f957686-79be-4c59-9afd-6460a5c68d1a",
                            TwoFactorEnabled = false,
                            UserName = "user@vls.com"
                        },
                        new
                        {
                            Id = "d8eb2df5-8f9c-4eef-9b8a-19f0260a0b01",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f46335f3-77d6-4705-9c3e-5ca57e04dd19",
                            Email = "moderator@vls.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "MODERATOR@VLS.COM",
                            NormalizedUserName = "MODERATOR@VLS.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEIA61EsotEyK392gG0grdteQaW6nkS6pLxzXTSSJOM5TrwlAOXUz1Zl5w/fi+02/ZQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "6c91e300-0f96-403c-9898-5bcf00d26f23",
                            TwoFactorEnabled = false,
                            UserName = "moderator@vls.com"
                        },
                        new
                        {
                            Id = "a6d23e6d-83fe-41bb-9d73-1d04aec4d56c",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ddc2b77f-01bb-4674-bd6b-a28b3c2bcc61",
                            Email = "admin@vls.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@VLS.COM",
                            NormalizedUserName = "ADMIN@VLS.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEMb16uSEw1i9JgUjBnXwpjYWUgeL13aj5jJlhS/XdahZLa3JLrPwz8dyTk9y00dHcQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "920c4a7f-4a2f-4492-aa3e-b059314b29e3",
                            TwoFactorEnabled = false,
                            UserName = "admin@vls.com"
                        });
                });

            modelBuilder.Entity("VelvetLeaves.Data.Models.AppPreferences", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("BackgroundUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FaviconUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RootProductsName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("AppPreferences");
                });

            modelBuilder.Entity("VelvetLeaves.Data.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ImageId")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageId = "64be89ae1409e5a61554e6ed",
                            IsActive = true,
                            Name = "Jewelry"
                        },
                        new
                        {
                            Id = 2,
                            ImageId = "64be8c9f41c19cda7ab19853",
                            IsActive = true,
                            Name = "Textile"
                        });
                });

            modelBuilder.Entity("VelvetLeaves.Data.Models.Color", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ColorValue")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.ToTable("Colors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ColorValue = "#ff0000",
                            IsActive = true,
                            Name = "Red"
                        },
                        new
                        {
                            Id = 2,
                            ColorValue = "#0000ff",
                            IsActive = true,
                            Name = "Blue"
                        },
                        new
                        {
                            Id = 3,
                            ColorValue = "#00ff00",
                            IsActive = true,
                            Name = "Green"
                        });
                });

            modelBuilder.Entity("VelvetLeaves.Data.Models.Gallery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("ImageId")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Galleries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Handcrafted jewelry made of silk cocoons",
                            ImageId = "64be8c870b7f086367ebb6a5",
                            IsActive = true,
                            Name = "Silk Cocoons"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Handcrafted jewelry made of glass",
                            ImageId = "64be8c9332b088f8d6063040",
                            IsActive = true,
                            Name = "Glass"
                        });
                });

            modelBuilder.Entity("VelvetLeaves.Data.Models.GalleryProduct", b =>
                {
                    b.Property<int>("GalleryId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.HasKey("GalleryId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("GalleriesProducts");

                    b.HasData(
                        new
                        {
                            GalleryId = 1,
                            ProductId = 1,
                            Position = 1
                        },
                        new
                        {
                            GalleryId = 1,
                            ProductId = 2,
                            Position = 2
                        },
                        new
                        {
                            GalleryId = 1,
                            ProductId = 3,
                            Position = 3
                        },
                        new
                        {
                            GalleryId = 2,
                            ProductId = 4,
                            Position = 1
                        });
                });

            modelBuilder.Entity("VelvetLeaves.Data.Models.Image", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Image");

                    b.HasData(
                        new
                        {
                            Id = "64be89ae1409e5a61554e6ed",
                            ProductId = 1
                        },
                        new
                        {
                            Id = "64be8c68cac3fdf11a06fbbb",
                            ProductId = 1
                        },
                        new
                        {
                            Id = "64be8c6df878c3764a814981",
                            ProductId = 1
                        },
                        new
                        {
                            Id = "64be8c733df251037e15d70a",
                            ProductId = 2
                        },
                        new
                        {
                            Id = "64be8c7a0ef21ca57c247498",
                            ProductId = 2
                        },
                        new
                        {
                            Id = "64be8c813d909293463359d6",
                            ProductId = 2
                        },
                        new
                        {
                            Id = "64be8c870b7f086367ebb6a5",
                            ProductId = 3
                        },
                        new
                        {
                            Id = "64be8c8d7d5c466b820b73af",
                            ProductId = 3
                        },
                        new
                        {
                            Id = "64be8c9332b088f8d6063040",
                            ProductId = 4
                        },
                        new
                        {
                            Id = "64be8c99f991d074063b5098",
                            ProductId = 4
                        },
                        new
                        {
                            Id = "64be8c9f41c19cda7ab19853",
                            ProductId = 5
                        },
                        new
                        {
                            Id = "64be8ca5b7f1ea12383c364a",
                            ProductId = 5
                        },
                        new
                        {
                            Id = "64be8caa293917f47210277e",
                            ProductId = 6
                        },
                        new
                        {
                            Id = "64be8cae1813d7aff61e173b",
                            ProductId = 6
                        },
                        new
                        {
                            Id = "64be8cb3b390e17c62039322",
                            ProductId = 7
                        },
                        new
                        {
                            Id = "64be8cb81a39dd6ed0351ebb",
                            ProductId = 7
                        });
                });

            modelBuilder.Entity("VelvetLeaves.Data.Models.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.ToTable("Materials");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Silver"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "Steel"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "Glass"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Name = "Textile"
                        });
                });

            modelBuilder.Entity("VelvetLeaves.Data.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderStatus")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("VelvetLeaves.Data.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductSeriesId")
                        .HasColumnType("int");

                    b.Property<int>("SubcategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductSeriesId");

                    b.HasIndex("SubcategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Red earrings with silver frames.",
                            IsActive = true,
                            Name = "Red Silver Earrings",
                            Price = 50.00m,
                            ProductSeriesId = 1,
                            SubcategoryId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Red-blue earrings with steel frames.",
                            IsActive = true,
                            Name = "Red-Blue Steel Earrings",
                            Price = 45.00m,
                            ProductSeriesId = 2,
                            SubcategoryId = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "Green necklace with a silver frame.",
                            IsActive = true,
                            Name = "Green Silver Necklace",
                            Price = 35.00m,
                            ProductSeriesId = 3,
                            SubcategoryId = 2
                        },
                        new
                        {
                            Id = 4,
                            Description = "Blue ring made out of glass and silver.",
                            IsActive = true,
                            Name = "Blue Glass Ring",
                            Price = 25.00m,
                            ProductSeriesId = 4,
                            SubcategoryId = 3
                        },
                        new
                        {
                            Id = 5,
                            Description = "Hand bag with traditional sewing pattern.",
                            IsActive = true,
                            Name = "Traditional Hand Bag",
                            Price = 120.00m,
                            ProductSeriesId = 5,
                            SubcategoryId = 4
                        },
                        new
                        {
                            Id = 6,
                            Description = "Hand bag with traditional sewing pattern.",
                            IsActive = true,
                            Name = "Traditional Hand Bag",
                            Price = 120.00m,
                            ProductSeriesId = 5,
                            SubcategoryId = 4
                        },
                        new
                        {
                            Id = 7,
                            Description = "Blue book binding.",
                            IsActive = true,
                            Name = "Blue Book Binding",
                            Price = 70.00m,
                            ProductSeriesId = 6,
                            SubcategoryId = 5
                        });
                });

            modelBuilder.Entity("VelvetLeaves.Data.Models.ProductSeries", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("DefaultDescription")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("DefaultName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("DefaultPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("SubcategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubcategoryId");

                    b.ToTable("ProductSeries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DefaultDescription = "Earrings with silver frames.",
                            DefaultName = "Silver Earrings",
                            DefaultPrice = 50.00m,
                            IsActive = true,
                            Name = "Silver Earrings",
                            SubcategoryId = 1
                        },
                        new
                        {
                            Id = 2,
                            DefaultDescription = "Earrings with steel frames.",
                            DefaultName = "Steel Earrings",
                            DefaultPrice = 50.00m,
                            IsActive = true,
                            Name = "Steel Earrings",
                            SubcategoryId = 1
                        },
                        new
                        {
                            Id = 3,
                            DefaultDescription = "Necklace with a silver frame.",
                            DefaultName = "Silver Necklace",
                            DefaultPrice = 50.00m,
                            IsActive = true,
                            Name = "Silver Necklace",
                            SubcategoryId = 2
                        },
                        new
                        {
                            Id = 4,
                            DefaultDescription = "Ring made out of glass and silver.",
                            DefaultName = "Glass Ring",
                            DefaultPrice = 50.00m,
                            IsActive = true,
                            Name = "Glass Ring",
                            SubcategoryId = 3
                        },
                        new
                        {
                            Id = 5,
                            DefaultDescription = "Hand bag with traditional sewing pattern.",
                            DefaultName = "Traditional Bag",
                            DefaultPrice = 50.00m,
                            IsActive = true,
                            Name = "Traditional Bag",
                            SubcategoryId = 4
                        },
                        new
                        {
                            Id = 6,
                            DefaultDescription = "Book binding.",
                            DefaultName = "Book Binding",
                            DefaultPrice = 50.00m,
                            IsActive = true,
                            Name = "Book Binding",
                            SubcategoryId = 5
                        });
                });

            modelBuilder.Entity("VelvetLeaves.Data.Models.Subcategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ImageId")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Subcategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            ImageId = "64be89ae1409e5a61554e6ed",
                            IsActive = true,
                            Name = "Earings"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            ImageId = "64be8c870b7f086367ebb6a5",
                            IsActive = true,
                            Name = "Necklaces"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            ImageId = "64be8c9332b088f8d6063040",
                            IsActive = true,
                            Name = "Rings"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            ImageId = "64be8ca5b7f1ea12383c364a",
                            IsActive = true,
                            Name = "Bags"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            ImageId = "64be8cb3b390e17c62039322",
                            IsActive = true,
                            Name = "Book Bindings"
                        });
                });

            modelBuilder.Entity("VelvetLeaves.Data.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Traditional Sewing Pattern"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "Silk Cocoons"
                        });
                });

            modelBuilder.Entity("ApplicationUserProduct", b =>
                {
                    b.HasOne("VelvetLeaves.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ApplicationUsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VelvetLeaves.Data.Models.Product", null)
                        .WithMany()
                        .HasForeignKey("FavoritesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ColorProductSeries", b =>
                {
                    b.HasOne("VelvetLeaves.Data.Models.Color", null)
                        .WithMany()
                        .HasForeignKey("DefaultColorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VelvetLeaves.Data.Models.ProductSeries", null)
                        .WithMany()
                        .HasForeignKey("ProductSeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("VelvetLeaves.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("VelvetLeaves.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VelvetLeaves.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("VelvetLeaves.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OrderProduct", b =>
                {
                    b.HasOne("VelvetLeaves.Data.Models.Order", null)
                        .WithMany()
                        .HasForeignKey("OrdersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VelvetLeaves.Data.Models.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProductsColors", b =>
                {
                    b.HasOne("VelvetLeaves.Data.Models.Color", null)
                        .WithMany()
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VelvetLeaves.Data.Models.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProductsMaterials", b =>
                {
                    b.HasOne("VelvetLeaves.Data.Models.Material", null)
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VelvetLeaves.Data.Models.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProductsSeriesMaterials", b =>
                {
                    b.HasOne("VelvetLeaves.Data.Models.Material", null)
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VelvetLeaves.Data.Models.ProductSeries", null)
                        .WithMany()
                        .HasForeignKey("ProductSeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProductsSeriesTags", b =>
                {
                    b.HasOne("VelvetLeaves.Data.Models.ProductSeries", null)
                        .WithMany()
                        .HasForeignKey("ProductSeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VelvetLeaves.Data.Models.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProductsTags", b =>
                {
                    b.HasOne("VelvetLeaves.Data.Models.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VelvetLeaves.Data.Models.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VelvetLeaves.Data.Models.Address", b =>
                {
                    b.HasOne("VelvetLeaves.Data.Models.ApplicationUser", "User")
                        .WithMany("Addresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VelvetLeaves.Data.Models.GalleryProduct", b =>
                {
                    b.HasOne("VelvetLeaves.Data.Models.Gallery", "Gallery")
                        .WithMany("GalleriesProducts")
                        .HasForeignKey("GalleryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VelvetLeaves.Data.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gallery");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("VelvetLeaves.Data.Models.Image", b =>
                {
                    b.HasOne("VelvetLeaves.Data.Models.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("VelvetLeaves.Data.Models.Order", b =>
                {
                    b.HasOne("VelvetLeaves.Data.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VelvetLeaves.Data.Models.ApplicationUser", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VelvetLeaves.Data.Models.Product", b =>
                {
                    b.HasOne("VelvetLeaves.Data.Models.ProductSeries", "ProductSeries")
                        .WithMany("Products")
                        .HasForeignKey("ProductSeriesId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("VelvetLeaves.Data.Models.Subcategory", "Subcategory")
                        .WithMany("Products")
                        .HasForeignKey("SubcategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductSeries");

                    b.Navigation("Subcategory");
                });

            modelBuilder.Entity("VelvetLeaves.Data.Models.ProductSeries", b =>
                {
                    b.HasOne("VelvetLeaves.Data.Models.Subcategory", "Subcategory")
                        .WithMany("ProductSeries")
                        .HasForeignKey("SubcategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subcategory");
                });

            modelBuilder.Entity("VelvetLeaves.Data.Models.Subcategory", b =>
                {
                    b.HasOne("VelvetLeaves.Data.Models.Category", "Category")
                        .WithMany("Subcategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("VelvetLeaves.Data.Models.ApplicationUser", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("VelvetLeaves.Data.Models.Category", b =>
                {
                    b.Navigation("Subcategories");
                });

            modelBuilder.Entity("VelvetLeaves.Data.Models.Gallery", b =>
                {
                    b.Navigation("GalleriesProducts");
                });

            modelBuilder.Entity("VelvetLeaves.Data.Models.Product", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("VelvetLeaves.Data.Models.ProductSeries", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("VelvetLeaves.Data.Models.Subcategory", b =>
                {
                    b.Navigation("ProductSeries");

                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
